export const uni = [
    "Indian Institute of Technology Bombay",
    "Indian Institute of Technology Kanpur",
    "University of Delhi",
    "Indian Institute of Technologyk",
    "Indian Institute of Technology Delhi",
    "Indian Institute of Technology Kharagpur",
    "Vellore Institute of Technology",
    "SRM Institute of Science and Technology",
    "Manipal Academy of Higher Education",
    "Narsee Monjee Institute of Management and Higher Studies",
    "Savitribai Phule Pune University",
    "Indian Institute of Science",
    "Amrita Vishwa Vidyapeetham",
    "Tata Institute of Fundamental Research",
    "International Institute of Information Technology, Hyderabad",
    "Lovely Professional University",
    "Amity University",
    "Jawaharlal Nehru University",
    "Birla Institute of Technology and Science",
    "University of Mumbai",
    "Anna University",
    "Panjab University",
    "Indian Institute of Technology Hyderabad",
    "Indian Statistical Institute",
    "Indian Institute of Technology Guwahati",
    "Chandigarh University",
    "Visvesvaraya Technological University",
    "Tata Institute of Social Sciences",
    "Christ University",
    "All India Institute of Medical Sciences Delhi",
    "Indian Institute of Technology Roorkee",
    "Aligarh Muslim University",
    "Banaras Hindu University",
    "Guru Gobind Singh Indraprastha University",
    "Tamil Nadu Agricultural University",
    "University of Calcutta",
    "The Maharaja Sayajirao University of Baroda",
    "Gujarat University",
    "University of Madras",
    "Jamia Millia Islamia",
    "Chitkara University, Punjab",
    "Kurukshetra University",
    "Osmania University",
    "University of Lucknow",
    "University of Kerala",
    "Dr. A.P.J. Abdul Kalam Technical University",
    "Cochin University of Science and Technology",
    "Indian Institute of Technology Gandhinagar	Chandkheda",
    "Maulana Abul Kalam Azad University of Technology, West Bengal",
    "University of Kashmir",
    "Gandhi Institute of Technology and Management",
    "Jadavpur University",
    "Jain University",
    "National Institute of Technology, Rourkela",
    "National Institute of Design",
   "National Institute of Technology, Tiruchirappalli",
   "Gujarat Technological University",
   "Tamil Nadu Teacher Education University",
   "University of Allahabad",
   "University of Calicut",
   "University of Petroleum and Energy Studies",
   "O.P. Jindal Global University",
   "Thapar Institute of Engineering and Technology",
   "Chennai Mathematical Institute",
   "SASTRA University",
   "Azim Premji University",
   "National Law School of India University",
   "Indian Institute of Science Education and Research, Pune",
   "Veer Narmad South Gujarat University",
   "National Institute of Technology, Calicut",
   "Shiv Nadar University",
   "University of Hyderabad",
   "University of Engineering and Management, Kolkata",
   "Ashoka University",
   "Indian Agricultural Research Institute",
   "National Institute of Fashion Technology",
   "Delhi Technological University",
   "University of Mysore",
   "University of Rajasthan",
   "National Institute of Technology, Karnataka	Mangalore",
   "Jawaharlal Nehru Technological University",
   "Mahatma Gandhi University",
   "International Institute of Information Technology Bangalore",
   "KIIT University",
   "APJ Abdul Kalam Technological University",
   "Chhatrapati Shahu Ji Maharaj University",
   "National Institute of Mental Health and Neuro Sciences",
   "M.J.P. Rohilkhand University",
   "Indian Institute of Information Technology Allahabad",
   "Indira Gandhi Institute of Development Research",
   "Birla Institute of Technology",
   "Guru Nanak Dev University",
   "Post Graduate Institute of Medical Education and Research",
   "Bharathidasan University",
   "Devi Ahilya Vishwavidyalaya",
   "BML Munjal University",
   "Motilal Nehru National Institute of Technology Allahabad",
   "Indian Institute of Space Science and Technology",
   "Jawaharlal Nehru Centre for Advanced Scientific Research",
    "Indian Institute of Technology Bhubaneswar",
"Pondicherry University",
"Bharathiar University",
"Sharda University",
"Indraprastha Institute of Information Technology",
"North Eastern Hill University",
"Chaudhary Charan Singh University",
"Indian Institute of Technology, BHU",
"Indian Institute of Technology Mandi",
"Dr. Vishwanath Karad MIT World Peace University",
"Indian Institute of Foreign Trade",
"Kannur University",
"Indian Institute of Science Education and Research, Kolkata",
"Rajiv Gandhi Proudyogiki Vishwavidyalaya",
"K L University",
"Annamalai University",
"Jiwaji University",
"University of Burdwan",
"Visva-Bharati University",
"Saurashtra University",
"Sanjay Gandhi Post Graduate Institute of Medical Sciences",
"Indian Institute of Technology Patna",
"ITM University Raipur",
"Nirma University",
"Bennett University	",
"Alagappa University",
"Indian Institute of Technology Jodhpur",
"Andhra University",
"Madurai Kamaraj University",
"West Bengal University of Health Sciences",
"CEPT University",
"Malaviya National Institute of Technology, Jaipur",
"Kerala Agricultural University	",
"Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
"Sant Gadge Baba Amravati University",
"University of Jammu",
"Dr. B R Ambedkar National Institute of Technology Jalandhar",
"Indian Institute of Technology Indore",
"Symbiosis International University",
"National Institute of Technology, Silchar",
"Indian School of Mines",
"University of Kalyani",
"Bangalore University",
"Dhirubhai Ambani Institute of Information and Communication Technology",
"Indian Institute of Technology Ropar",
"Hemwati Nandan Bahuguna Garhwal University",
"Atal Bihari Vajpayee Vishwavidyalaya",
"Presidency University",
"Maharashtra University of Health Sciences",
"National Law University, Delhi",
"Hemchandracharya North Gujarat University",
"Sathyabama Institute of Science and Technology",
"Govind Ballabh Pant University of Agriculture and Technology",
"Karunya Institute of Technology and Sciences",
"Jamia Hamdard",
"Ahmedabad University",
"Sri Ramachandra Institute of Higher Education and Research",
"Indian Institute of Engineering Science and Technology, Shibpur",
"Sardar Vallabhbhai National Institute of Technology, Surat",
"Gauhati University",
"Patna University",
"Jawaharlal Institute of Postgraduate Medical Education and Research",
"Alliance University",
"Kavayitri Bahinabai Chaudhari North Maharashtra University	",
"NITTE University",
"Hindustan Institute of Technology and Science",
"Indian Institute of Science Education and Research, Thiruvananthapuram",
"Gokhale Institute of Politics and Economics",
"Dr. Ram Manohar Lohia Avadh University",
"Sardar Patel University",
"Shivaji University",
"National Institute of Technology, Durgapur",
"Graphic Era University",
"Flame University",
"National Institute of Technology, Warangal",
"Rabindra Bharati University",
"Parul University",
"Babasaheb Bhimrao Ambedkar University",
"Ambedkar University Delhi",
"Visvesvaraya National Institute of Technology",
"Himachal Pradesh University",
"PES University",
"NALSAR University of Law",
"Punjabi University Patiala",
"Maulana Azad National Institute of Technology",
"Bharati Vidyapeeth Deemed University",
"University of North Bengal",
"Dibrugarh University",
"All India Institute of Medical Sciences Raipur",
"Gujarat National Law University",
"Rashtrasant Tukadoji Maharaj Nagpur University",
"Lalit Narayan Mithila University",
"Punjab Agricultural University",
"Vidyasagar University",
"KLE Technological University",
"Swami Ramanand Teerth Marathwada University",
"Rajasthan University of Health Sciences",
"Goa University",
"National Law University, Jodhpur",
"King George's Medical University",
"International Institute for Population Sciences",
"The West Bengal National University of Juridical Sciences",
"Assam Agricultural University",
"Shoolini University of Biotechnology and Management Sciences",
"Mangalore University",
"Rajiv Gandhi University of Health Sciences	",
"Sree Chitra Thirunal Institute of Medical Sciences and Technology",
"All India Institute of Medical Sciences Patna",
"South Asian University",
"Indian Institute of Science Education and Research, Bhopal",
"Invertis University",
"Jawaharlal Nehru Technological University, Kakinada",
"Rashtriya Sanskrit Sansthan University",
"Galgotias University",
"Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya",
"Pandit Ravishankar Shukla University",
"Padmashree Dr. D.Y. Patil Vidyapith",
"National Institute of Educational Planning and Administration",
"Sikkim Manipal University",
"University of Kota",
"ITM University Gwalior",
"Banasthali Vidyapith",
"Maharaja Krishnakumarsinhji Bhavnagar University",
"PEC University of Technology",
"TERI School of Advanced Studies",
"Institute of Chemical Technology",
"University of Agricultural Sciences, Bangalore",
"Baba Farid University of Health Sciences",
"Barkatullah University",
"Indian Institute of Science Education and Research, Mohali",
"All India Institute of Medical Sciences Jodhpur",
"Veer Bahadur Singh Purvanchal University",
"Tezpur University",
"National Institute of Technology, Jamshedpur",
"Jaypee Institute of Information Technology",
"Central University of Kashmir",
"Bundelkhand University	",
"Mahatma Gandhi Kashi Vidyapeeth",
"REVA University",
"National Institute of Technology, Patna",
"National Institute of Technology, Hamirpur",
"Pandit Deendayal Petroleum University",
"The LNM Institute of Information Technology",
"Rani Durgavati Vishwavidyalaya",
"Siksha 'O' Anusandhan",
"National Institute of Technology, Agartala",
"Indian Maritime University",
"Kerala University of Health Sciences",
"Bidhan Chandra Krishi Vishwavidyalaya",
"Assam Don Bosco University",
"National Institute of Technology, Raipur",
"DIT University",
"Motherhood University",
"National Institute of Technology, Kurukshetra",
"Dayalbagh Educational Institute",
"Deen Dayal Upadhyay Gorakhpur University",
"Punjab Technical University",
"NIIT University",
"Rajiv Gandhi University of Knowledge Technologies",
"National Institute of Technology, Srinagar",
"Mohanlal Sukhadia University",
"Dr. Bhimrao Ambedkar University",
"Tamil Nadu Dr. M.G.R.Medical University",
"Vels University",
"National Dairy Research Institute",
"Ganpat University",
"The IIS University",
"Veer Surendra Sai University of Technology",
"Vinayaka Mission's Research Foundation",
"Jaipur National University",
"Acharya Nagarjuna University",
"Indian Institute of Information Technology and Management Gwalior",
"Jaypee University of Information Technology",
"XIM University	",
"The Northcap University",
"Pt. Bhagwat Dayal Sharma University of Health Sciences",
"Acharya N.G. Ranga Agricultural University",
"Dr. D.Y. Patil Vidyapeeth",
"Maulana Azad National Urdu University",
"Indian Veterinary Research Institute",
"K.R. Mangalam University",
"Shri Mata Vaishno Devi University",
"JSS Academy of Higher Education and Research",
"Dr. Babasaheb Ambedkar Marathwada University",
"Ramaiah University of Applied Sciences",
"Rajasthan Technical University Kota",
"Indira Gandhi Krishi Vishwavidyalaya",
"Yenepoya University",
"Gandhigram Rural University",
"Brainware University",
"School of Planning and Architecture, Delhi",
"Anand Agricultural University",
"The National University of Advanced Legal Studies",
"Janardan Rai Nagar Rajasthan Vidhyapeeth University",
"Maharishi Markandeshwar University, Mullana",
"Periyar University",
"Bharath Institute of Higher Education and Research",
"The English and Foreign Languages University",
"Gujarat Ayurved University",
"Gujarat Vidyapith	",
"Assam Down Town University	",
"PDPM Indian Institute of Information Technology, Design and Manufacturing",
"Maharaja Ganga Singh University",
"Central University of South Bihar",
"Mizoram University",
"Sri Sathya Sai Institute of Higher Learning",
"Kakatiya University",
"Central University of Tamil Nadu",
"Kuvempu University",
"Manipur University",
"Rama University",
"All India Institute of Medical Sciences Bhopal",
"Tamil Nadu Veterinary and Animal Sciences University",
"Central University of Rajasthan",
"All India Institute of Medical Sciences Rishikesh",
"Manonmaniam Sundaranar University",
"Sri Venkateswara Institute of Medical Sciences",
"Shreemati Nathibai Damodar Thackersey Women's University",
"Nalanda University",
"Central University of Haryana",
"Ranchi University",
"Saveetha Institute of Medical and Technical Sciences",
"Siddharth University",
"Tripura University",
"Dharmsinh Desai University",
"Assam University",
"Central University of Punjab",
"Kerala Kalamandalam",
"Integral University",
"All India Institute of Medical Sciences Bhubaneswar",
"Presidency University",
"National Law Institute University",
"National Institute of Technology, Meghalaya",
"Dr. Shakuntala Misra National Rehabilitation University",
"B.S. Abdur Rahman Crescent Institute of Science and Technology",
"The Indian Law Institute",
"National Institute of Pharmaceutical Education and Research, S.A.S. Nagar",
"Rajiv Gandhi University",
"Pravara Institute of Medical Sciences",
"Maharishi Dayanand University",
"Islamic University of Science and Technology",
"Tamil Nadu Dr Ambedkar Law University",
"Karnatak University",
"Mody University of Science and Technology	",
"National Institute of Food Technology Entrepreneurship and Management",
"Pandit Deendayal Upadhyaya Shekhawati University",
"Jai Narain Vyas University",
"Magadh University",
"Centurion University of Technology and Management",
"Nagaland University",
"Madhav University	",
"National Institute of Technology, Delhi",
"Nizam's Institute of Medical Sciences",
"Biju Patnaik University of Technology",
"VIT Bhopal University",
"Teerthanker Mahaveer University",
"Dr. Rajendra Prasad Central Agricultural University",
"Assam Science and Technology University",
"Utkal University",
"Swami Vivekanand Subharti University",
"Indian Institute of Information Technology, Design and Manufacturing",
"Dr. Babasaheb Ambedkar Technological University",
"Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir",
"CSK Himachal Pradesh Krishi Vishvavidyalaya",
"MIT Art Design and Technology University",
"Central University of Jharkhand",
"Apeejay Stya University",
"SRM University Haryana	",
"CMR University	",
"Guru Ghasidas Vishwavidyalaya",
"Jawaharlal Nehru Krishi Vishwavidyalaya",
"JK Lakshmipat University",
"GD Goenka University",
"Noida International University	",
"Shree Guru Gobind Singh Tricentenary University",
"Jawaharlal Nehru Technological University, Anantapur",
"Kalasalingam Academy of Research and Education",
"Mahatma Gandhi University, Nalgonda",
"Central University of Karnataka",
"IFHE Hyderabad	",
"Adamas University",
"Indira Gandhi National Tribal University",
"Sri Venkateswara University",
"Chaudhary Charan Singh Haryana Agricultural University	",
"Chanakya National Law University",
"Odisha University of Agriculture and Technology",
"Madan Mohan Malaviya University of Technology",
"Sikkim University",
"Sidho Kanho Birsha University",
"NIMS University",
"Ramakrishna Mission Vivekananda Educational and Research Institute",
"University of Agricultural Sciences, Dharwad",
"Navsari Agricultural University",
"Gautam Buddha University",
"Avantika University",
"GLA University	",
"Central University of Kerala",
"JECRC University",
"Central University of Gujarat",
"Junagadh Agricultural University",
"Suresh Gyan Vihar University	",
"National Law University ",
"Hidayatullah National Law University",
"Deenbandhu Chhotu Ram University of Science and Technology",
"Sam Higginbottom Institute of Agriculture, Technology and Sciences",
"National Institute of Pharmaceutical Education and Research, Hyderabad	",
"Homi Bhabha National Institute",
"Rajiv Gandhi National Institute of Youth Development",
"Dr. Hari Singh Gour University	",
"North Eastern Regional Institute of Science and Technology",
"Dayananda Sagar University",
"Guru Jambheshwar University of Science and Technology",
"Babasaheb Bhimrao Ambedkar Bihar University",
"Maharaja Chhatrasal Bundelkhand University",
"Chhattisgarh Swami Vivekananda Technical University",
"Berhampur University",
"Dr. Ram Manohar Lohiya National Law University",
"Vignan University",
"Vikram University",
"Dr. M.G.R. Educational and Research Institute",
"Karnavati University",
"Central University of Odisha",
"Central University of Himachal Pradesh",
"Maharshi Dayanand Saraswati University",
"Rashtriya Raksha University	",
"Sant Longowal Institute of Engineering and Technology",
"Dr. Y.S. Parmar University of Horticulture and Forestry",
"Rajiv Gandhi National University of Law",
"Sri Krishnadevaraya University	",
"Indira Gandhi Delhi Technical University for Women",
"National Institute of Technology, Arunachal Pradesh",
"Cotton University",
"Aliah University",
"Indian Institute of Information Technology, Sri City",
"National Institute of Technology, Goa",
"Adikavi Nannaya University",
"Marwadi University",
"National Institute of Technology, Puducherry",
"Quantum University",
"Vinoba Bhave University",
"Prof. Rajendra Singh (Rajju Bhaiya) University",
"Krishna University",
"Indian Institute of Teacher Education",
"KLE University",
"Cluster University of Jammu",
"Charotar University of Science and Technology",
"Awadhesh Pratap Singh University",
"Graphic Era Hill University",
"Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya",
"National Institute of Technology, Mizoram",
"Swami Vivekananda Yoga Anusandhana Samsthana",
"Tilak Maharashtra Vidyapeeth",
"Rajiv Gandhi Institute of Petroleum Technology",
"University of Gour Banga",
"Uttaranchal University",
"Dev Sanskriti Vishwavidyalaya",
"Jawaharlal Nehru Architecture and Fine Arts University",
"Yogi Vemana University",
"Central Institute of Fisheries Education",
"Sarguja University",
"Shri Govind Guru University",
"National Institute of Technology, Manipu",
"Tilka Manjhi Bhagalpur University",
"J.C. Bose University of Science and Technology",
"Uttarakhand Technical University",
"RK University",
"Guru Angad Dev Veterinary and Animal Sciences University",
"National Institute of Technology, Uttarakhand",
"Sambalpur University",
"Kumaun University",
"Cooch Behar Panchanan Barma University	",
"Sri Sri University",
"Kalinga University",
"Garden City University",
"Sri Balaji Vidyapeeth",
"Dr. N.T.R. University of Health Sciences",
"Singhania University",
"Ajeenkya D.Y. Patil University",
"Lingaya's University",
"Kerala University of Fisheries and Ocean Studies",
"National Institute of Technology, Sikkim",
"Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya",
"School of Planning and Architecture, Vijayawada",
"Doon University",
"ICFAI University, Tripura",
"Harcourt Butler Technical University",
"Sandip University",
"IEC University	",
"Sage University",
"National University of Study and Research in Law",
"Himachal Pradesh Technical University",
"Maharana Pratap University of Agriculture and Technology",
"Avinashilingam University",
"Rayalaseema University",
"Kolhan University",
"Dravidian University",
"School of Planning and Architecture, Bhopal",
"Central Institute of Higher Tibetan Studies",
"Swarnim Gujarat Sports University",
"Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth",
"Indian Institute of Information Technology, Vadodara",
"Kazi Nazrul University",
"Assam Rajiv Gandhi University of Cooperative Management",
"National Institute of Pharmaceutical Education and Research, Ahmedabad",
"Birsa Agricultural University",
"Anant National University",
"Central University of Jammu",
"Chaudhary Devi Lal University",
"Techno India University",
"Tamil University",
"Professor Jayashankar Telangana State Agricultural University",
"Potti Sreeramulu Telugu University",
"Jagannath University",
"Forest Research Institute",
"Aryabhatta Knowledge University",
"National Institute of Technology, Nagaland",
"Rishihood University",
"Gurukul Kangri Vishwavidyalaya",
"Dr. C.V. Raman University",
"Karnataka Veterinary, Animal and Fisheries Sciences University",
"Deccan College Post-Graduate and Research Institute",
"Indian Institute of Information Technology, Guwahati",
"Dr. Panjabrao Deshmukh Krishi Vidyapeeth",
"Kerala Veterinary and Animal Sciences University",
"Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha",
"Shobhit Institute of Engineering and Technology",
"Vivekananda Global University",
"Tumkur University",
"Mahatma Phule Krishi Vidyapeeth",
"Sri Padmavati Mahila Visvavidyalayam",
"G.L.S. University",
"Tamil Nadu Dr. J. Jayalalithaa Fisheries University",
"Lakshmibai National Institute of Physical Education",
"IIMT University",
"Poornima University",
"National Law University and Judicial Academy",
"Jain Vishva Bharati Institute",
"Chitkara University, Himachal Pradesh",
"Chandra Shekhar Azad University of Agriculture and Technology",
"Thiruvalluvar University",
"Shri Vishwakarma Skill University",
"Indira Gandhi Institute of Medical Sciences",
"Mahatma Gandhi Central University, Motihari",
"Babu Banarasi Das University",
"Damodaram Sanjivayya National Law University",
"IIHMR University",
"Himalayan University",
"Uka Tarsadia University",
"Gulbarga University",
"Vishwakarma University",
"Bihar Agricultural University",
"Rai University",
"West Bengal University of Animal and Fishery Sciences",
"Sree Sankaracharya University of Sanskrit",
"Datta Meghe Institute of Medical Sciences",
"Uttar Banga Krishi Viswavidyalaya",
"Maharaja Surajmal Brij University",
"Sardar Vallabhbhai Patel University of Agriculture and Technology",
"Rajasthan University of Veterinary and Animal Sciences",
"Jagran Lakecity University",
"West Bengal University of Teachers' Training, Education Planning and Administration",
"Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu	",
"DAV University",
"Sanskriti University",
"Indus University",
"West Bengal State University",
"Himgiri ZEE University",
"Mother Teresa Women's University",
"Sri Venkateswara Veterinary University",
"Karpagam Academy of Higher Education",
"Indira Gandhi University, Meerpur",
"Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya",
"Bhakta Kavi Narsinh Mehta University",
"Satavahana University",
"St. Xavier's University",
"Ravenshaw University",
"ICFAI University, Dehradun",
"Tamil Nadu Physical Education and Sports University",
"Maharashtra National Law University, Nagpur",
"Sher-i-Kashmir Institute of Medical Sciences",
"Sir Padampat Singhania University",
"MATS University",
"Veer Kunwar Singh University",
"International Institute of Information Technology, Bhubaneswar",
"Mewar University",
"People's University",
"MIT University",
"Jaypee University of Engineering and Technology",
"Kaziranga University",
"Glocal University",
"Jharkhand Rai University",
"Jayoti Vidyapeeth Women's University",
"Krantiguru Shyamji Krishna Verma Kachchh University",
"Mangalayatan University",
"Telangana University",
"Maharashtra Animal and Fishery Sciences University",
"Medi-Caps University",
"Dr. B.R. Ambedkar University",
"International Institute of Information Technology, Naya Raipur",
"AURO University",
"Raj Rishi Bharthari Matsya University",
"Vasantrao Naik Marathwada Krishi Vidyapeeth",
"Raja Mansingh Tomar Music and Arts University",
"Lala Lajpat Rai University of Veterinary and Animal Sciences",
"University of Trans-Disciplinary Health Sciences and Technology",
"Periyar Maniammai Institute of Science and Technology",
"Rani Channamma University, Belagavi",
"RKDF University",
"Nanaji Deshmukh Veterinary Science University",
"Dakshina Bharat Hindi Prachar Sabha",
"Indian Institute of Information Technology, Lucknow",
"Swami Keshwanand Rajasthan Agricultural University",
"Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
"Thunchath Ezhuthachan Malayalam University",
"Swami Rama Himalayan University",
"Sri Guru Granth Sahib World University",
"JIS University",
"Maharashtra National Law University Mumbai",
"Sushant University	",
"Career Point University",
"Binod Bihari Mahto Koyalanchal University",
"Ponnaiyan Ramajayam Institute of Science and Technology",
"Kamdhenu University",
"BLDE University",
"Kannada University",
"Karnataka State Women's University",
"Krishna Institute of Medical Sciences",
"Shri Venkateshwara University",
"National Sports University",
"Fakir Mohan University",
"RIMT University",
"Delhi Pharmaceutical Sciences and Research University",
"Uttar Pradesh University of Medical Sciences",
"Mahatma Gandhi University, Meghalaya",
"Maharaja Ranjit Singh Punjab Technical University",
"Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry",
"Central Agricultural University",
"GNA University",
"Sri Dev Suman Uttarakhand University",
"Rashtriya Sanskrit Vidyapeetha",
"Srimanta Sankaradeva University of Health Sciences",
"OPJS University",
"Tamil Nadu National Law University",
"Karnataka Samskrit University",
"North Orissa University",
"Bhupendra Narayan Mandal University",
"LNCT University",
"Pacific University, India",
"Institute of Infrastructure, Technology, Research and Management",
"Palamuru University",
"Navrachana University",
"Chaudhary Ranbir Singh University",
"Maharishi University of Management and Technology",
"Indian Institute of Information Technology, Pune",
"MGM Institute of Health Sciences",
"University of Agricultural Sciences, Raichur",
"Vikrama Simhapuri University",
"Bankura University",
"Raiganj University	",
"Rabindranath Tagore University",
"Shri Vaishnav Vidyapeeth Vishwavidyalaya",
"Indian Institute of Public Health",
"National Institute of Pharmaceutical Education and Research, Guwahati",
"Symbiosis University of Applied Sciences",
"Sangam University",
"Karnataka State Law University",
"ICFAI University, Jharkhand",
"Gujarat Forensic Sciences University",
"Sardar Patel University of Police, Security and Criminal Justice",
"Davangere University",
"IMS Unison University",
"U.P. Pt. Deen Dayal Upadhyaya Veterinary Science University and Cattle Research Institute",
"Dr. Y.S.R. Horticultural University",
"Dr K.N. Modi University",
"Arunachal University of Studies",
"Chaudhary Bansi Lal University",
"Indian Institute of Information Technology, Kottayam",
"Indira Kala Sangeet Vishwavidyalaya",
"Suamandeep Vidyapeeth",
"National Institute of Pharmaceutical Education and Research, Rae Bareli",
"University of Horticultural Sciences, Bagalkot",
"University of Science and Technology, Meghalaya",
"Santosh University",
"Bhagwant University",
"Mahatma Jyoti Rao Phoole University",
"Alakh Prakash Goyal Shimla University",
"Jodhpur National University",
"University of Technology",
"Desh Bhagat University	Mandi",
"Institute of Advanced Studies in Education	",
"Banda University of Agriculture and Technology",
"Maharishi University",
"Shri Ramswaroop Memorial University",
"Sardarkrushinagar Dantiwada Agricultural University",
"Hemwati Nandan Bahuguna Uttarakhand Medical Education University",
"ISBM University",
"PDM University",
"Bhagat Phool Singh Mahila Vishwavidyalaya",
"Children's University",
"Oriental University",
"Nava Nalanda Mahavihara",
"Maharshi Panini Sanskrit Vishwavidyalaya",
"O.P. Jindal University",
"Gangadhar Meher University",
"Bodoland University",
"Indian Institute of Information Technology, Manipur",
"Uttarakhand Sanskrit University",
"Kameshwar Singh Darbhanga Sanskrit University",
"Manipur Technical University",
"Rani Lakshmi Bai Central Agricultural University",
"Ayush and Health Sciences University of Chhattisgarh",
"University of Agricultural and Horticultural Sciences, Shivamogga",
"Indian Institute of Information Technology, Kalyani",
"Vijayanagara Sri Krishnadevaraya University",
"Gondwana University",
"University of Patanjali",
"Sri Devaraj Urs Academy of Higher Education and Research",
"Indian Institute of Information Technology, Una",
"GIET University",
"Chhattisgarh Kamdhenu Vishwavidyalaya",
"Jagan Nath University",
"ICFAI University, Sikkim",
"Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya",
"Dr. B.R. Ambedkar University of Social Sciences",
"St. Peter's Institute of Higher Education and Research",
"EIILM University",
"National Institute of Pharmaceutical Education and Research, Kolkata",
"Sido Kanhu Murmu University",
"IFTM University",
"Bastar Vishwavidyalaya",
"Shridhar University",
"Punyashlok Ahilyadevi Holkar University, Solapur",
"Uttarakhand Ayurved University",
"P P Savani University",
"Kushabhau Thakre Patrakarita Avam Jansanchar University",
"Narendra Dev University of Agriculture and Technology",
"Jagadguru Ramanandacharya Rajasthan Sanskrit University",
"Mahatma Gandhi University of Medical Sciences and Technology",
"Rayat-Bahra University",
"Baba Ghulam Shah Badhshah University",
"Shri Jagannath Sanskrit Vishvavidyalaya",
"Nilamber-Pitamber University",
"AKS University	",
"MVN University",
"Sri Siddhartha Academy of Higher Education",
"Sri Satya Sai University of Technology and Medical Sciences",
"JSS Science and Technology University",
"Dr. Sarvepalli Radhakrishnan Rajasthan Ayurved University",
"Sabarmati University",
"ITM Vocational University",
"Maulana Mazharul Haque Arabic and Persian University",
"Himalayan Garhwal University",
"Adesh University",
"ICFAI University, Jaipur",
"Jagadguru Rambhadracharya Handicapped University",
"Eternal University	",
"Kadi Sarva Vishwavidyalaya",
"Srinivas University",
"Sampurnanand Sanskrit Vishvavidyalaya",
"Govind Guru Tribal University",
"Bhartiya Skill Development University",
"Martin Luther Christian University",
"Raffles University",
"Shree Somnath Sanskrit University",
"Bengaluru North University	",
"Utkal University of Culture",
"Baddi University of Emerging Sciences and Technologies	",
"Maharashtra National Law University, Aurangabad	",
"Diamond Harbour Women's University	",
"Manav Bharti University",
"Rama Devi Women's University",
"G.H. Raisoni University",
"Mohammad Ali Jauhar University",
"Sunrise University",
"Mandsaur University",
"The Neotia University",
"Monad University",
"Meenakshi Academy of Higher Education and Research",
"Sri Venkateswara Vedic University",
"Dr. A.P.J Abdul Kalam University",
"Atmiya University",
"Sri Konda Laxman Telangana State Horticultural University",
"Swami Vivekanand University",
"Spicer Adventist University",
"Apex University",
"Maharishi Markandeshwar University, Solan",
"Seacom Skills University",
"Sanjay Ghodawat University",
"Kumar Bhaskar Varma Sanskrit and Ancient Studies University",
"National Institute of Pharmaceutical Education and Research, Hajipur",
"Apex Professional University",
"ICFAI University, Raipur",
"Atal Bihari Vajpayee Hindi Vishwavidyalaya",
"Bhatkhande Music Institute",
"Guru Kashi University",
"Maharaja Bir Bikram University	",
"JS University	",
"GSFC University",
"Arni University",
"North East Frontier Technical University",
"Baba Mastnath University",
"Madhyanchal Professional University",
"Sai Nath University",
"Indrashil University",
"Rajiv Gandhi National Aviation University",
"NIILM University",
"Swarnim Startup and Innovation University",
"Sankalchand Patel University",
"Shri Jagdishprasad Jhabrmal Tibrewala University",
"Pratap University",
"Jananayak Chandrashekhar University",
"Era University	",
"ICFAI University, Mizoram",
"C.U. Shah University",
"The Sanskrit College and University",
"TeamLease Skills University",
"Sanchi University of Buddhist-Indic Studies",
"Institute of Advanced Research",
"Sri Sai University	",
"Jai Prakash Vishwavidyalaya",
"Assam Women's University",
"Sarvepalli Radhakrishnan University",
"Arka Jain University",
"Tantia University",
"BAHRA University",
"Guru Ravidas Ayurved University",
"KSGH Music and Performing Arts University",
"Khallikote University Berhampur",
"Sarala Birla University",
"Murshidabad University",
"Maharaja Agrasen University",
"Al-Falah University",
"Akal University",
"Uttarakhand Aawasiya Vishwavidyalaya, Almora",
"ICFAI University, Meghalaya",
"ICFAI University, Himachal Pradesh	",
"Mahapurusha Srimanta Sankaradeva Viswavidyalaya",
"Sant Baba Bhag Singh University",
"Starex University",
"Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya",
"Bhupal Nobles University",
"Indus International University",
"ICFAI University, Nagaland",
"Rai Technology University",
"Central University of Andhra Pradesh",
"Usha Martin University",
"Nehru Gram Bharati Vishwavidyalaya",
"Bareilly International University",
"Pacific Medical University",
"Sri Guru Ram Das University of Health Sciences	Qila Jiwan Singh",
"Maharishi Arvind University, Jaipur",
"Karnataka Janapada Vishwavidyalaya",
"Shri Guru Ram Rai University",
"Karnataka State Rural Development and Panchayat Raj University",
"Maharishi Markandeshwar University, Sadopur",
"Jaypee University Anoopshahr",
"Vinayaka Missions Sikkim University",
"William Carey University, Meghalaya",
"Malwanchal University",
"K.K. University	",
"Pragyan International University",
"Plastindia International University",
"Gujarat University of Transplantation Sciences",
"Sharnbasva University",
"SRM University, Sikkim",
"State University of Performing and Visual Arts",
"YBN University	",
"Geetanjali University",
"Khwaja Moinuddin Chishti Language University",
"Lakulish Yoga University",
"St. Joseph University",
"P.K. University",
"Abhilashi University",
"Tamil Nadu Dr.J Jayalalithaa Music and Fine Arts University",
"Sangai International University",
"Sai Tirupati University",
"Haridev Joshi University of Journalism and Mass Communication",
"Arunodaya University",
"CMJ University",
"Indira Gandhi Technological and Medical Sciences University",
"Ras Bihari Bose Subharti University",
"Maulana Azad University, Jodhpur",
"Dr YSR Architecture and Fine Arts University",
"Manipur International University",
"Jharkhand Raksha Shakti University",
"Manipur University of Culture",
"Shri Guru Ram Rai Education Mission",
"Manav Rachna International Institute of Research and Studies",
"Manav Rachna University	",
"Sandip University, Sijoul"

]